//Core
import {useEffect, useState} from "react";
import Head from 'next/head';
import Image from 'next/image';

import {BsSearch} from "react-icons/bs";

import image1 from "@assets/images/dommies/eventCenter1.png";
import image2 from "@assets/images/dommies/eventCenter2.jpeg";
import image3 from "@assets/images/dommies/eventCenter3.png";
import Card from "@components/Card/Card";
import Link from "next/link";
import useSwr from 'swr';

const fetcher = (url) => fetch(url).then((res) => res.json())

export default function Home() {

    const {data: eventCenters, error} = useSwr('/api/twitter/event-centers', fetcher);

    const [searchTerm, setSearchTerm] = useState("");
    const [searchResults, setSearchResults] = useState([]);

    const handleChange = event => {
        setSearchTerm(event.target.value);
    };

    useEffect(() => {

        const results = eventCenters ? eventCenters.filter(eventCenter =>
            eventCenter.nombre_centro.toLowerCase().includes(searchTerm)
        ) : [];
        setSearchResults(results);

        console.log(searchResults);

    }, [eventCenters, searchTerm]);

    const imagesDivs = !eventCenters ? [] : searchResults.map(({
                                       event_center_id,
                                       descripcion_centro,
                                       fiestas_list,
                                       imagen_centro,
                                       nombre_centro,
                                       ranking,
                                   }, i) => (
        <Card key={i} imageUrl={imagen_centro} title={nombre_centro}
              description={descripcion_centro}
              actions={(
                  <Link href={`/eventCenter/${event_center_id}`}><a className="btn btn-secondary">Visitar</a></Link>
              )}
        />
    ));
    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className="container grid gap-8">
                <div className={"relative w-full max-w-2xl m-auto flex items-center"}>
                    <input className={"pl-12 w-full"} id="username" type="text" placeholder={"Buscar..."}
                           onChange={handleChange}/>
                    <span className={"absolute text-base text-gray-500 left-4"}><BsSearch/></span>
                </div>
                <div className={"grid-cards"}>
                    {imagesDivs}
                </div>
            </div>
        </>
    )
}
